# Generated by Django 3.0.3 on 2020-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=200)),
                ('filter_class', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('key', models.CharField(max_length=50)),
                ('github_url', models.URLField(verbose_name='Github URL')),
                ('photo', models.ImageField(default='portfolio/default.png', upload_to='portfolio/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
